### ISSUE TITLE
Error when starting a simulation with a previously saved file

### ISSUE THREAD

**Issue by chernan** [epilog-tool/epilog#3]
Hi all,
I have an error starting a simulation with a model created with one of the latest v0.5 nightly builds. I can open the file and see all parameters correctly, but when starting the simulation I get this error

`
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.epilogtool.core.topology.TopologyHexagon.includesNeighbour(TopologyHexagon.java:52)
	at org.epilogtool.core.topology.TopologyHexagon.getPositionNeighbours(TopologyHexagon.java:25)
	at org.epilogtool.integration.IFEvaluation.traverseTreeISEvaluate(IFEvaluation.java:157)
	at org.epilogtool.integration.IFEvaluation.traverseTreeISEvaluate(IFEvaluation.java:107)
	at org.epilogtool.integration.IFEvaluation.traverseTreeIFEvaluate(IFEvaluation.java:74)
	at org.epilogtool.integration.IFEvaluation.traverseTreeIFEvaluate(IFEvaluation.java:46)
	at org.epilogtool.integration.IFEvaluation.traverseTreeIFEvaluate(IFEvaluation.java:55)
	at org.epilogtool.integration.IFEvaluation.evaluate(IFEvaluation.java:28)
	at org.epilogtool.project.Simulation.nextCellValue(Simulation.java:201)
	at org.epilogtool.project.Simulation.nextStepGrid(Simulation.java:133)
	at org.epilogtool.project.Simulation.getGridAt(Simulation.java:246)
	at org.epilogtool.gui.tab.EpiTabSimulation.simulationStepFwr(EpiTabSimulation.java:686)
	at org.epilogtool.gui.tab.EpiTabSimulation.access$200(EpiTabSimulation.java:59)
	at org.epilogtool.gui.tab.EpiTabSimulation$3.actionPerformed(EpiTabSimulation.java:197)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`
I didn't have this error when I first created the model four weeks ago, as I was able to run quite a few simulations then. Now that I try to re-use the file, I have the error on both v0.5 and v1.0.

I can provide a small test file by email.

Cheers,
Céline

**Comment by PedroBLV** [comment]
Hi Celine, can you send me the file?

Thanks!

**Comment by chernan** [comment]
I just did. :)
Thank you!
